// <auto-generated />
using FastVoteMachine.Services.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastVoteMachine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220323201455_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ConnectionEntityVoteEntity", b =>
                {
                    b.Property<int>("ConnectionsConnectionEntityId")
                        .HasColumnType("int");

                    b.Property<int>("VotesVoteEntityId")
                        .HasColumnType("int");

                    b.HasKey("ConnectionsConnectionEntityId", "VotesVoteEntityId");

                    b.HasIndex("VotesVoteEntityId");

                    b.ToTable("ConnectionEntityVoteEntity");
                });

            modelBuilder.Entity("FastVoteMachine.Services.Entities.ConnectionEntity", b =>
                {
                    b.Property<int>("ConnectionEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Connection")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ConnectionEntityId");

                    b.ToTable("connections");
                });

            modelBuilder.Entity("FastVoteMachine.Services.Entities.OptionEntity", b =>
                {
                    b.Property<int>("OptionEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VoteEntityId")
                        .HasColumnType("int");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("OptionEntityId");

                    b.HasIndex("VoteEntityId");

                    b.ToTable("options");
                });

            modelBuilder.Entity("FastVoteMachine.Services.Entities.VoteEntity", b =>
                {
                    b.Property<int>("VoteEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VoteEntityId");

                    b.ToTable("votes");
                });

            modelBuilder.Entity("ConnectionEntityVoteEntity", b =>
                {
                    b.HasOne("FastVoteMachine.Services.Entities.ConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("ConnectionsConnectionEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastVoteMachine.Services.Entities.VoteEntity", null)
                        .WithMany()
                        .HasForeignKey("VotesVoteEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastVoteMachine.Services.Entities.OptionEntity", b =>
                {
                    b.HasOne("FastVoteMachine.Services.Entities.VoteEntity", null)
                        .WithMany("Options")
                        .HasForeignKey("VoteEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastVoteMachine.Services.Entities.VoteEntity", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
